# Generated by Django 3.2.7 on 2021-09-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todolist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateTimeField(verbose_name='Deadline'),
        ),
    ]
